### ISSUE TITLE
InviteCensor Not Working

### ISSUE THREAD

**Issue by 8ur4k** [SinisterDeveloper/discord-moderation-bot#10]
When someone send invite link to server there is no action on bot and see this error on terminal:

"Unhandled promise rejection: TypeError: server.fetchInvites is not a function
    at /Users/{USER}/repos/others/discord-moderation-bot/events/inviteCensor.js:11:24
    at new Promise (<anonymous>)
    at isInvite (/Users/{USER}/repos/others/discord-moderation-bot/events/inviteCensor.js:10:26)
    at Object.execute (/Users/{USER}/repos/others/discord-moderation-bot/events/inviteCensor.js:28:39)
    at Client.<anonymous> (/Users/{USER}/repos/others/discord-moderation-bot/index.js:24:56)
    at Client.emit (node:events:538:35)
    at MessageCreateAction.handle (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:526:28)
    at Receiver.receiverOnMessage (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/ws/lib/websocket.js:970:20)
    at Receiver.emit (node:events:526:28)
    at Receiver.dataMessage (/Users/{USER}/repos/others/discord-moderation-bot/node_modules/ws/lib/receiver.js:502:14)"

1. Run project on dev
2. Try send invite link from an acc
3. Check terminal for error

 I get this error on Mac Mini M1.

**Comment by aestriex** [comment]
I don't believe that SinisterDeveloper is supporting this project anymore.

**Comment by 8ur4k** [comment]
> I don't believe that SinisterDeveloper is supporting this project anymore.

I think so. So I need to bring this repo to life by myself :3

**Comment by 8ur4k** [comment]
Btw I think I solve the problem. Just make sure your "inviteCensor.js" look like this; 

```
module.exports = {
    name: `messageCreate`,
    async execute(message) {
        if (message.author.bot || !message.guild) return;
        if (message.channel.permissionsFor(message.member).has(`ADMINISTRATOR`)) return; // Checks if the member is server admin

        const { content } = message;

        if (content.includes('discord.gg/')) {
                await message.delete();
                await message.channel.send({ content: `Invite links are not allowed here ${message.member}.` })
                    .then(resultMessage => {
                    function sleep(ms) {
                        return new Promise(
                            resolve => setTimeout(resolve, ms));
                    }
                    sleep(5000)
                        .then(() => {
                            resultMessage.delete();
                        });
                });
        }
    }
};
```

**Comment by SinisterDeveloper** [comment]
Hey @8ur4k,
Sorry I was unavailable for the last 3 years due to some personal commitments. I'll look over the issue and fix it.
I saw your code, and although it is not wrong, it deletes messages containing _any invite link_, including your own server's

Although it was raised 2 years ago, I’m now working on a resolution to ensure the repository remains fully functional so thank you for addressing it

**Comment by SinisterDeveloper** [comment]
@8ur4k @aestriex The issue has been fixed in the latest release
